Iter5
Erlast/short-url pull request #5
Opened 2024-05-01 12:36 UTC by Erlast

2024-05-03 09:48 UTC, s-shpak requested changes
Т.к. я буду твоим ревьюером добавь, пожалуйста, `golangci-lint` в проект и поправь его замечания (см. здесь https://app.pachca.com/chats/9180496?message=230119157). Если какие-то будут непонятными - пиши

2024-05-03 09:48 UTC, s-shpak commented on cmd/shortener/main.go
В пакете `main` должен лежать код, который позволяет запустить сервис (чуть позже добавим штатное завершение). Тебе необходиом добиться, чтобы пакет был как можно более компактным: получение конфигурации, инициализация и запуск сервера и все. Всю остальную логику необходимо перенести в `internal`

2024-05-03 09:48 UTC, s-shpak commented on cmd/shortener/main.go
> +var storage map[string]string
Глобальные переменные не нужны. Сделай хранилище частью структуры, которая его использует

2024-05-03 09:48 UTC, s-shpak commented on go.mod
> +go 1.21.9
```suggestion
go 1.22.0
```

2024-05-03 09:48 UTC, s-shpak commented on cmd/shortener/main.go
> +var conf config.Cfg
См. комментарий про глобальные переменные выше

2024-05-03 09:48 UTC, s-shpak commented on cmd/shortener/main.go
> +		panic(err)
Паниковать не надо, прокидывай ошибку (возвращая ее из функции) до самого верха стека (до `func main() {}`) и завершай выполнение приложения при помощи `log.Fatal`

2024-05-03 09:48 UTC, s-shpak commented on cmd/shortener/main.go
> +func checkHandler(res http.ResponseWriter, req *http.Request) {
Как только ты начала использовать `chi` эта функция стала ненужой: роутер проверяет путь за тебя

2024-05-03 09:48 UTC, s-shpak commented on cmd/shortener/main.go
> +	sb := strings.Builder{}
Слишком сложно, используй просто слайс длины `n` и записывай символы по индексу

2024-05-03 09:48 UTC, s-shpak commented on cmd/shortener/main.go
> +	id := strings.Replace(req.URL.Path, "/", "", 1)
`chi` дает тебе доступ к параметру, тебе не надо извлекать его самостоятельно. См. здесь, например: https://github.com/go-chi/chi?tab=readme-ov-file#request-handlers

2024-05-03 09:48 UTC, s-shpak commented on cmd/shortener/main.go
> +		http.Error(res, "Not Found!", http.StatusNotFound)
Здесь из кода надо выйти

2024-05-03 09:48 UTC, s-shpak commented on cmd/shortener/main.go
> +	url, err := storage[id]
`err` принято использовать для ошибок, для проверок используют `ok`

```suggestion
	url, ok := storage[id]
```

2024-05-03 09:48 UTC, s-shpak commented on cmd/shortener/main.go
> +	defer func(Body io.ReadCloser) {
Серверу не требуется закрывать `body` запроса

2024-05-03 09:48 UTC, s-shpak commented on cmd/shortener/main.go
> +		http.Error(res, "Empty String!", http.StatusBadRequest)
Когда ты вызываешь `http.Error` ты не завершаешь выполнение функции. Тебе надо добавить `return` сразу после

2024-05-03 09:48 UTC, s-shpak commented on cmd/shortener/main.go
> +	storage[rndString] = string(u)
Что если такая случайная строка уже есть в хранилище ?

2024-05-03 09:48 UTC, s-shpak commented on cmd/shortener/main.go
> +	str := conf.FlagBaseURL + "/" + rndString
Лучше использовать это: https://pkg.go.dev/net/url#JoinPath

2024-05-03 09:48 UTC, s-shpak commented on cmd/shortener/main.go
> +		http.Error(res, "Something went wrong!", http.StatusBadRequest)
1. Это `ServerInternalError`
2. Если мы не смогли записать ответ первый раз, то маловероятно, что запишем в ответ ошибку о том, что ответ не полусилось записать. Здесь достаточно залогировать ошибку и выйти

2024-05-03 09:48 UTC, s-shpak commented on internal/config/config.go
> +	flag.StringVar(&Config.FlagRunAddr, "a", ":8080", "port to run server")
Дефолтное значение определено также на строке `21`, попробуй не дублировать эти значения, иначе они могут "разъехаться"

2024-05-03 09:48 UTC, s-shpak commented on internal/config/config.go
> +		log.Fatal(err)
Фаталиться здесь нельзя, Fatal надо прокидывать наверх и там завершаться

2024-05-04 16:22 UTC, s-shpak reviewed
Добавь golangci-lint в github actions: https://github.com/s-shpak/praktikum-golangci-lint?tab=readme-ov-file#настройка-github-actions

2024-05-04 16:22 UTC, s-shpak commented on internal/app/config/config.go
> +		fmt.Println("failed:", err)
1. Не надо использовать `fmt.Println`, используй `log`
2. Если произошла проблема при получении конфигурации, то лучше завершиться с ошибкой

2024-05-04 16:22 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +var settings Settings
Глобальные переменные не нужны

2024-05-04 16:22 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +	err = req.Body.Close()
Запросы не надо закрывать, сервер делает это самостоятельно

2024-05-04 16:22 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +		GenerateRandom(ln)
1. Не надо использовать рекурсию
2. Это может быть бесконечным цилом. Если не получается `n` раз, то лучше выкинуть ошибку

2024-05-04 16:22 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +func GenerateRandom(ln int) string {
Зачем эта функция экспортируется ?

2024-05-04 16:22 UTC, s-shpak commented on internal/app/storages/storage.go
> +func Init(u map[string]string) Storage {
Почему бы не позволить Storage самому инициализировать мапу: сейчас инициализация извне нарушает инкапсуляцию

2024-05-04 16:22 UTC, s-shpak commented on internal/app/storages/storage.go
> +	Urls map[string]string
Не надо экспортировать это поле, объяви методы в объекте `Storage`, которые будут добавлять и возвращать элементы

2024-05-05 09:50 UTC, Erlast commented
Добавила в коллобараторы, должен инвайт прийти

2024-05-05 13:57 UTC, s-shpak requested changes

2024-05-05 13:57 UTC, s-shpak commented on internal/app/config/config.go
> +func (conf *Cfg) GetBaseURL() string {
В Go не принято использовать геттеры и сеттеры

2024-05-05 13:57 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +	return rndString
А что если после трех попыток не получилось сгенерировать short url ?

2024-05-05 13:57 UTC, s-shpak commented on internal/app/storages/storage.go
> +func Init() *Storage {
В Go конструктор принято называть `NewStorage`

2024-05-05 13:57 UTC, s-shpak commented on internal/app/storages/storage.go
> +		return "", errors.New("not found")
В ошибки стоит добавлять информацию о контексте ошибки:

```suggestion
		return "", fmt.Errorf("short URL %s was not found", id)
```

2024-05-05 13:57 UTC, s-shpak commented on internal/app/routes/route.go
> +func Init(store *storages.Storage, conf *config.Cfg) *chi.Mux {
См. комментарий про именование конструкторов

2024-05-06 12:37 UTC, s-shpak requested changes

2024-05-06 12:37 UTC, s-shpak commented on internal/app/config/config.go
> +	if flag.Lookup("a") == nil {
Зачем эта проверка ?

2024-05-06 12:37 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +		if _, ok := storage.GetByID(rndString); ok == nil {
1. Переменные хранящие ошибки принято называть `err`
2. Если такая короткая URL существует, ты сразу вернешь ошибку, а не повторишь действие 3 раза

2024-05-06 12:37 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +		http.Error(res, err.Error(), http.StatusBadRequest)
Это не `BadRequest`. Проверь другие ошибки тоже, некторые из них - InternalServerError

2024-05-06 12:50 UTC, Erlast commented on internal/app/config/config.go
> +	if flag.Lookup("a") == nil {
без этой проверки тесты падают и выдает ошибку ``` flag redefined: a ```

2024-05-07 07:22 UTC, s-shpak commented on internal/app/config/config.go
> +	if flag.Lookup("a") == nil {
Так быть не должно. Попробуй сначала парсить флаги при помощи:

```golang
flag.StringVar(...)
...
flag.Parse()
```

А потом выставлять определенные переменные окружения.

Так точно должно получиться без лукапов

2024-05-07 07:26 UTC, s-shpak requested changes

2024-05-07 07:26 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +		http.Error(res, err.Error(), http.StatusInternalServerError)
Пользователю нельзя возвращать эту ошибку, но ее надо залогировать

2024-05-07 07:26 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +	if _, err := storage.GetByID(rndString); err == nil {
Не понимаю логику. Допустим ты смогла сгенерировать `rndString` в цикле. Зачем тогда этот вызов ? Допустим ты не смогла сгенерировать `rndString` в цикле. Тогда ты уже попробовала три раза, зачем пытаться снова ?

2024-05-07 08:31 UTC, Erlast commented on internal/app/config/config.go
> +	if flag.Lookup("a") == nil {
так он ругается на StringVar, я уже так делала без лукапов, тест падает во втором случае, когда произвожу повторную инициализацию. https://stackoverflow.com/questions/49193480/golang-flag-redefined. Изменила подход к тестам. Без лукапов в конфиге. Но повторюсь еще раз, если инициализировать два раза конфиг эти проверки необходимы.

2024-05-07 13:46 UTC, s-shpak commented on internal/app/config/config.go
> +	if flag.Lookup("a") == nil {
Все получилось, ура :)

2024-05-07 13:53 UTC, s-shpak requested changes

2024-05-07 13:53 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +		http.Error(res, "Something went wrong!", http.StatusInternalServerError)
Ошибки `Internal Server Error` должны логироваться

2024-05-07 13:53 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +		fmt.Println(err.Error())
1. Не используй `fmt`, используй `log`
2. Если не вызвать `http.Error`, то сервер автоматически ответит пользователю `OK`. Выставить `Interal Server Error` надо, но не надо возвращать текст ошибки. Текстом должно быть что-то типа `Something went wrong!`, как у тебя выше

2024-05-07 13:53 UTC, s-shpak commented on internal/app/handlers/handlers.go
>  		rndString = helpers.RandomString(ln)
Вызови это под `for range 3` и тебе не нужна будет строка 72

2024-05-09 05:25 UTC, s-shpak requested changes

2024-05-09 05:25 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +		log.Println(errorText)
Идея логирования заключается в том, что нам как разработчикам можно посмотреть, что произошло, когда что-то пошло не так. То есть в лог нам надо поместить текст ошибки, а пользователю вернуть какое-то общее сообщение.

То есть что-то такое:

```suggestion
		log.Printf("failed to read the request body: %v", err)
		http.Error(res, "", http.StatusInternalServerError)
```

2024-05-10 13:24 UTC, s-shpak requested changes

2024-05-10 13:24 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +		http.Error(res, "Something went wrong!", http.StatusInternalServerError)
Почему иногда ничего, а иногда `Something went wrong!`

2024-05-10 14:35 UTC, s-shpak approved these changes

2024-05-14 08:26 UTC, merged